services:
  postgres:
    image: postgres:17-alpine
    container_name: mt_postgres
    environment:
      POSTGRES_DB: movieweb
      POSTGRES_USER: hamza
      POSTGRES_PASSWORD: "1111"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
      - mt-network
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U hamza -d movieweb"]
      interval: 10s
      timeout: 5s
      retries: 5

  redis:
    image: redis:7-alpine
    container_name: mt_redis
    networks:
      - mt-network
    healthcheck:
      test: ["CMD", "redis-cli", "ping"]
      interval: 10s
      timeout: 5s
      retries: 5
    volumes:
      - redis_data:/data

  app:
    build:
      dockerfile: Dockerfile
      context: .
    container_name: mt_app
    environment:
      SPRING_DATASOURCE_URL: jdbc:postgresql://postgres:5432/movieweb
      SPRING_DATASOURCE_USERNAME: hamza
      SPRING_DATASOURCE_PASSWORD: "1111"
      SPRING_REDIS_HOST: redis
      SPRING_REDIS_PORT: "6379"
    ports:
      - "3839:3839"
    depends_on:
      postgres:
        condition: service_healthy
      redis:
        condition: service_healthy
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:3839/movies"]
      interval: 10s
      timeout: 5s
      retries: 5
    volumes:
      - ./uploads:/app/uploads
    networks:
      - mt-network

volumes:
  postgres_data:
  redis_data:

networks:
  mt-network:
    driver: bridge
