spring.application.name=MT


spring.datasource.url=jdbc:postgresql://localhost:5432/movieweb
spring.datasource.username=hamza
spring.datasource.password=1111
spring.datasource.driver-class-name=org.postgresql.Driver

# ===============================
# JPA / Hibernate
# ===============================
spring.jpa.database-platform=org.hibernate.dialect.PostgreSQLDialect
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true

# ===============================
# File Upload Configuration
# ===============================
spring.servlet.multipart.max-file-size=10MB
spring.servlet.multipart.max-request-size=10MB
app.upload.dir=uploads/

server.port=3839


jwt.secret=9F2xK8QmR4ZyE6A1D7JHn5UoCPLbS0tYwXMVaGkW3Bq
jwt.expirationMs=86400000

